### ISSUE TITLE
Improve Website UI

### ISSUE THREAD

**Issue by OindrilaDas27** [GDSC-IIIT-Kalyani/Plot#1]
- [ ] Add icons to the respective tools 
- [ ] Add hover effect on all the tools
- [ ] Improve the over all UI

**Comment by priyanshu6781** [comment]
Hey, I want to work on this.

**Comment by srijoy-paul** [comment]
@OindrilaDas27 I would like to work on this, can you assign me this issue ?

**Comment by OindrilaDas27** [comment]
Issue has been assigned to @priyanshu6781 on fsfc basis. You have 48hrs until this passes to the person next in line

**Comment by Urmilasc** [comment]
Hello , I want to contribute , if possible than assign to me

**Comment by srijoy-paul** [comment]
@OindrilaDas27 If assigned person is not working then, Please assign this to me
As I have commented before
