### ISSUE TITLE
Make website responsive

### ISSUE THREAD

**Issue by OindrilaDas27** [GDSC-IIIT-Kalyani/Plot#2]
Ask to be assigned the issue

**Comment by Abhijeet03s** [comment]
@OindrilaDas27 I want to work on this. Please assign it to me.

**Comment by srijoy-paul** [comment]
@OindrilaDas27  Can you assign me this issue?

**Comment by srijoy-paul** [comment]
I am working on it

**Comment by srijoy-paul** [comment]
@OindrilaDas27 I have made the PR #14 , please review it
