### ISSUE TITLE
Fix website UI

### ISSUE THREAD

**Issue by OindrilaDas27** [GDSC-IIIT-Kalyani/Plot#29]
The current UI is overlapping with the previous UI
![image](https://user-images.githubusercontent.com/96684483/195023341-8353df18-c1a1-42d7-a5b4-a24fafe72937.png)

It should look like:
![image](https://user-images.githubusercontent.com/96684483/195023464-b26462a0-144a-4717-8058-58aa9b1daa5f.png)

**Comment by manav-06** [comment]
Hi, @OindrilaDas27 you can assign this to me

**Comment by SRIMANKS** [comment]
you can assign this to me

**Comment by OindrilaDas27** [comment]
The issue has been assigned to @manav-06 on fcfs basis. It'll be assigned to @SRIMANKS  if manav fails to resolve it in 48hrs.

**Comment by OindrilaDas27** [comment]
issue assigned to @SRIMANKS
