### ISSUE TITLE
Create new empty color boxes

### ISSUE THREAD

**Issue by OindrilaDas27** [GDSC-IIIT-Kalyani/Plot#5]
Ask to be assigned the issue
Add 4 more empty color boxes under the existing boxes

**Comment by srijoy-paul** [comment]
@OindrilaDas27 Please assign me this task?

**Comment by sidmadke** [comment]
@OindrilaDas27 I can do this task instantly. Please assign me.

**Comment by OindrilaDas27** [comment]
@sidmadke you've been assigned the task. Complete it in 48hrs or it will be assigned to the person next in line

**Comment by srijoy-paul** [comment]
@OindrilaDas27 I have commented first

**Comment by OindrilaDas27** [comment]
> @OindrilaDas27 I have commented first, it was fcfs basis right?
Hi, I have already assigned you in one issue. It'd be fair to give others a chance too

**Comment by sidmadke** [comment]
@OindrilaDas27 I have made the PR #13 
Do consider merging it
